<a href="https://colab.research.google.com/github/VM-Janani/Linear-Algebra-The-Coding-Way/blob/main/Eigenvalues%20and%20Eigenvectors/EigenValuesVectors_Notebook2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sympy as sp

In [ ]:
def eigenvalue_eigenvector(matrix):
  # Calculate eigenvalues and eigenvectors
  eigenvalues, eigenvectors = np.linalg.eig(matrix)
  # Print the result
  print("Eigenvalues:", eigenvalues)
  print("Eigenvectors:", eigenvectors)
  eig_matrix_sympy = sp.Matrix(eigenvectors)

  # Compute the reduced row echelon form (RREF)
  rref = eig_matrix_sympy.rref()
  print("\nRREF:")
  print(rref[0])

  #calculate the number of non-zero rows
  non_zero_rows = np.count_nonzero(rref[0])
  print("\nNumber of non-zero rows:", non_zero_rows)

  # Check if eigenvectors are linearly independent
  if non_zero_rows == min(matrix.shape):
      unique_elements = np.unique(eigenvalues)
      if len(unique_elements) == len(eigenvalues):
          print("\nThe Eigenvalues are distinct & the Eigenvectors are linearly independent.")
      else:
          print("\nThe Eigenvalues are not distinct but the Eigenvectors are linearly independent.")
  else:
      print("\nThe Eigenvalues are not distinct & the Eigenvectors are linearly dependent.")



 Eigenvalues are distinct & the Eigenvectors are linearly independent

In [ ]:
# Define the matrix
A = np.array([[2, 1,0],
              [1, 3,-1],
              [0,-1,4]])
eigenvalue_eigenvector(A)

Eigenvalues: [1.26794919 3.         4.73205081]
Eigenvectors: [[-0.78867513 -0.57735027 -0.21132487]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.21132487 -0.57735027  0.78867513]]

RREF:
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

Number of non-zero rows: 3

The Eigenvalues are distinct & the Eigenvectors are linearly independent.


The Eigenvalues are not distinct but the Eigenvectors are linearly independent

In [ ]:
# Define the matrix
A1 = np.array([[2, 1,0],
              [0, 2,1],
              [0,0,2]])
eigenvalue_eigenvector(A1)

Eigenvalues: [2. 2. 2.]
Eigenvectors: [[ 1.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  4.44089210e-16 -4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  1.97215226e-31]]

RREF:
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

Number of non-zero rows: 3

The Eigenvalues are not distinct but the Eigenvectors are linearly independent.


In [ ]:
#define the matrix
A2 = np.array([[2, 0],
               [0, 2]])
eigenvalue_eigenvector(A2)

Eigenvalues: [2. 2.]
Eigenvectors: [[1. 0.]
 [0. 1.]]

RREF:
Matrix([[1, 0], [0, 1]])

Number of non-zero rows: 2

The Eigenvalues are not distinct but the Eigenvectors are linearly independent.
